# Generated by Django 2.0 on 2018-03-05 17:26

import casting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('second_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=None, max_length=20, unique=True)),
                ('age', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=128)),
                ('prof', models.CharField(choices=[('amateur', 'Amateur'), ('professional', 'Professional')], max_length=128)),
                ('experience', models.TextField(blank=True, max_length=1000, null=True)),
                ('grouping', models.BooleanField(default=False)),
                ('crowd_scene', models.BooleanField(default=False)),
                ('about_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to=casting.models.get_image_path)),
                ('video_url', models.CharField(max_length=70)),
            ],
        ),
    ]
