# Generated by Django 2.0 on 2018-03-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='person',
            name='prof',
            field=models.CharField(max_length=70),
        ),
    ]
