# Generated by Django 2.0 on 2018-03-06 15:45

import casting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0002_auto_20180305_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_image',
            field=models.ImageField(null=True, upload_to=casting.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
