# Generated by Django 2.0 on 2018-03-06 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0003_auto_20180306_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 17, 59, 47, 663907)),
        ),
    ]
