# Generated by Django 2.0 on 2018-03-07 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0004_person_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 2, 1, 30, 138555)),
        ),
    ]
