# Generated by Django 2.0 on 2018-03-07 00:16

import casting.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0005_auto_20180307_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_image',
            field=models.ImageField(blank=True, null=True, upload_to=casting.models.get_person_photo_path),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 2, 16, 10, 87714)),
        ),
    ]
