# Generated by Django 2.0 on 2018-03-07 21:41

import casting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0007_auto_20180307_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=casting.models.get_person_photo_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='contact_image',
        ),
        migrations.AddField(
            model_name='images',
            name='person',
            field=models.ForeignKey(default=None, on_delete=None, to='casting.Person'),
        ),
    ]
