# Generated by Django 2.0 on 2018-03-07 22:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0008_auto_20180307_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 22, 26, 2, 208325, tzinfo=utc)),
        ),
    ]
