# Generated by Django 2.0 on 2018-03-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0009_auto_20180308_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='about_info',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='video_url',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
