# Generated by Django 2.0 on 2018-03-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0010_auto_20180308_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=70)),
            ],
        ),
    ]
