# Generated by Django 2.0 on 2018-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0011_youvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='youvideo',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
