# Generated by Django 2.0 on 2018-03-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0012_youvideo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youvideo',
            old_name='video',
            new_name='video_id',
        ),
    ]
