# Generated by Django 2.0 on 2018-03-08 19:30

import casting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0013_auto_20180308_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=casting.models.get_person_photo_path)),
                ('about_info', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250)),
                ('about_info', models.TextField(blank=True, max_length=1000)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=casting.models.get_worker_photo_path)),
            ],
        ),
    ]
