# Generated by Django 2.0 on 2018-03-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0014_poster_worker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PersonImage',
        ),
    ]
