# Generated by Django 2.0 on 2018-03-08 22:18

import casting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0016_filmphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=casting.models.get_person_photo_path)),
                ('person', models.ForeignKey(default=None, on_delete=None, to='casting.Person')),
            ],
        ),
        migrations.RenameModel(
            old_name='YouVideo',
            new_name='YoutubeVideo',
        ),
        migrations.RemoveField(
            model_name='personimage',
            name='person',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='avatar',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='poster',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=casting.models.get_poster_photo_path),
        ),
        migrations.DeleteModel(
            name='PersonImage',
        ),
    ]
