# Generated by Django 2.0 on 2018-03-10 14:43

import casting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0017_auto_20180309_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=casting.models.get_partner_photo_path)),
                ('partner_url', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('social_id', models.CharField(blank=True, max_length=150)),
                ('social_url', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='video_url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
