# Generated by Django 2.0 on 2018-03-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0018_auto_20180310_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='languages',
            field=models.CharField(choices=[('ru', 'Russian'), ('ua', 'Ukrainian'), ('en', 'English')], default=('ru', 'Russian'), max_length=128),
        ),
        migrations.AddField(
            model_name='worker',
            name='languages',
            field=models.CharField(choices=[('ru', 'Russian'), ('ua', 'Ukrainian'), ('en', 'English')], default=('ru', 'Russian'), max_length=128),
        ),
    ]
