# Generated by Django 2.0 on 2018-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0019_auto_20180310_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
