# Generated by Django 2.0 on 2018-03-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0020_worker_is_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poster',
            new_name='Film_about',
        ),
    ]
