# Generated by Django 2.0 on 2018-03-15 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0022_auto_20180315_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
