# Generated by Django 2.0 on 2018-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0024_auto_20180315_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='user_data',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
