# Generated by Django 2.0 on 2018-03-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0025_userip_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
