# Generated by Django 2.0 on 2018-03-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0026_userip_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film_about',
            new_name='FilmAbout',
        ),
    ]
