# Generated by Django 2.0 on 2018-03-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0027_auto_20180316_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personphoto',
            name='person',
            field=models.OneToOneField(default=None, on_delete=None, to='casting.Person'),
        ),
    ]
