# Generated by Django 2.0 on 2018-03-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0028_auto_20180318_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personphoto',
            name='person',
            field=models.ForeignKey(default=None, on_delete=None, to='casting.Person'),
        ),
    ]
