# Generated by Django 2.0 on 2018-03-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0030_person_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personphoto',
            name='person',
            field=models.ForeignKey(default=None, on_delete=None, related_name='photos', to='casting.Person'),
        ),
    ]
