# Generated by Django 2.0 on 2018-03-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0031_auto_20180318_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmabout',
            name='about_info',
            field=models.TextField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='person',
            name='about_info',
            field=models.TextField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.TextField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='worker',
            name='about_info',
            field=models.TextField(blank=True, max_length=8000),
        ),
    ]
