# Generated by Django 2.0 on 2018-03-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0032_auto_20180318_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.CharField(default='name', max_length=250),
            preserve_default=False,
        ),
    ]
