# Generated by Django 2.0 on 2018-03-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0033_worker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmabout',
            name='languages',
            field=models.CharField(choices=[('ua', 'Ukrainian'), ('en', 'English')], default=('ua', 'Ukrainian'), max_length=128),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.UserIP', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='vote',
            field=models.SmallIntegerField(choices=[(-1, 'Dislike'), (1, 'Like')], verbose_name='Vote'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='languages',
            field=models.CharField(choices=[('ua', 'Ukrainian'), ('en', 'English')], default=('ua', 'Ukrainian'), max_length=128),
        ),
    ]
