# Generated by Django 2.0 on 2018-03-28 17:39

import casting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0034_auto_20180322_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmabout',
            options={'verbose_name': 'About film', 'verbose_name_plural': 'About film'},
        ),
        migrations.AlterModelOptions(
            name='filmphoto',
            options={'verbose_name': 'Film photos', 'verbose_name_plural': 'Film photos'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partners', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persons', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='personphoto',
            options={'verbose_name': 'Person photos', 'verbose_name_plural': 'Person photos'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Socials', 'verbose_name_plural': 'Socials'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Workers', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'verbose_name': 'Youtube videos', 'verbose_name_plural': 'Youtube videos'},
        ),
        migrations.AlterField(
            model_name='filmabout',
            name='about_info',
            field=models.TextField(blank=True, max_length=8000, verbose_name='About info'),
        ),
        migrations.AlterField(
            model_name='filmabout',
            name='languages',
            field=models.CharField(choices=[('ua', 'Ukrainian'), ('en', 'English')], default=('ua', 'Ukrainian'), max_length=128, verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='filmabout',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=casting.models.get_poster_photo_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='filmabout',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='filmphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=casting.models.get_film_photo_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='filmphoto',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_url',
            field=models.CharField(blank=True, max_length=150, verbose_name='Partner url'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=casting.models.get_partner_photo_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='person',
            name='about_info',
            field=models.TextField(blank=True, max_length=8000, verbose_name='About info'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=70, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='crowd_scene',
            field=models.BooleanField(default=False, verbose_name='Crowd scene'),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.TextField(blank=True, max_length=8000, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=70, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=70, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='grouping',
            field=models.BooleanField(default=False, verbose_name='Grouping'),
        ),
        migrations.AlterField(
            model_name='person',
            name='images',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='prof',
            field=models.CharField(max_length=70, verbose_name='Professionalism'),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_name',
            field=models.CharField(max_length=35, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='video_url',
            field=models.CharField(blank=True, max_length=150, verbose_name='Video url'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='person',
            field=models.ForeignKey(default=None, on_delete=None, related_name='photos', to='casting.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=casting.models.get_person_photo_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='social',
            name='social_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='Social id'),
        ),
        migrations.AlterField(
            model_name='social',
            name='social_url',
            field=models.CharField(blank=True, max_length=150, verbose_name='Social url'),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='about_info',
            field=models.TextField(blank=True, max_length=8000, verbose_name='About info'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='languages',
            field=models.CharField(choices=[('ua', 'Ukrainian'), ('en', 'English')], default=('ua', 'Ukrainian'), max_length=128, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=casting.models.get_worker_photo_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(max_length=250, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(max_length=70, verbose_name='Video id'),
        ),
    ]
