# Generated by Django 2.0 on 2018-04-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0035_auto_20180328_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_info', models.TextField(blank=True, max_length=8000, verbose_name='About info')),
                ('languages', models.CharField(choices=[('ua', 'Ukrainian'), ('en', 'English')], default=('ua', 'Ukrainian'), max_length=128, verbose_name='languages')),
            ],
            options={
                'verbose_name': 'Casting rules',
                'verbose_name_plural': 'Casting rules',
            },
        ),
    ]
