# Generated by Django 2.0 on 2018-04-09 22:14

import casting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0036_castingrules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Title')),
                ('about_info', models.TextField(blank=True, max_length=8000, verbose_name='About info')),
                ('link', models.CharField(blank=True, max_length=150, verbose_name='Social url')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=casting.models.get_news_photo_path, verbose_name='Photo')),
                ('languages', models.CharField(choices=[('ua', 'Ukrainian'), ('en', 'English')], default=('ua', 'Ukrainian'), max_length=128, verbose_name='languages')),
            ],
            options={
                'verbose_name': 'Casting news',
                'verbose_name_plural': 'Casting news',
            },
        ),
    ]
