# Generated by Django 2.0 on 2018-04-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0037_castingnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(default=None, max_length=20, verbose_name='Age'),
        ),
    ]
